#!/usr/bin/env bash

set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALL_SHARDS=(color vt cursor screen terminfo reader spinner prompt progress)
MANAGED_MARKER="generated by scripts/validate-shards.sh --local"

LOCAL_MODE=0
CLEAN_LOCAL=0
FORCE_OVERRIDES=0
ALLOW_EXISTING_OVERRIDES=0
SKIP_INSTALL=0
SKIP_SPECS=0
SKIP_EXAMPLES=0
LIST_SHARDS=0
SELECTED_SHARDS=("${ALL_SHARDS[@]}")

RESULTS=()
FAILURES=0

usage() {
  cat <<'USAGE'
Usage: scripts/validate-shards.sh [options]

Validate every crystal-term shard from the monorepo root.

Options:
  --local                     Write shard.override.yml files for local deps before validation.
  --clean-local-overrides     Remove generated shard.override.yml files and exit.
  --force-overrides           Replace existing shard.override.yml files in --local mode.
  --allow-existing-overrides  Allow unmanaged shard.override.yml files outside --local mode.
  --skip-install              Do not run shards install.
  --skip-specs                Do not run crystal spec.
  --skip-examples             Do not compile examples.
  --shards a,b,c              Validate only the named shards.
  --list-shards               Print shard names and paths, then exit.
  -h, --help                  Show this help.

Default shard order is dependency/release order:
  color, vt, cursor, screen, terminfo, reader, spinner, prompt, progress

The install phase is intentionally sequential to avoid shared Crystal/Shards
cache races when nested repositories are validated from the same checkout.
USAGE
}

shard_path() {
  case "$1" in
    color) printf '%s\n' "$ROOT_DIR/shards/color" ;;
    vt) printf '%s\n' "$ROOT_DIR/shards/vt" ;;
    cursor) printf '%s\n' "$ROOT_DIR/shards/cursor" ;;
    screen) printf '%s\n' "$ROOT_DIR/shards/screen" ;;
    terminfo) printf '%s\n' "$ROOT_DIR/shards/terminfo" ;;
    reader) printf '%s\n' "$ROOT_DIR/shards/reader" ;;
    spinner) printf '%s\n' "$ROOT_DIR/shards/spinner" ;;
    prompt) printf '%s\n' "$ROOT_DIR/shards/prompt" ;;
    progress) printf '%s\n' "$ROOT_DIR/shards/progress" ;;
    *) return 1 ;;
  esac
}

is_known_shard() {
  case "$1" in
    color|vt|cursor|screen|terminfo|reader|spinner|prompt|progress) return 0 ;;
    *) return 1 ;;
  esac
}

local_dependency_lines() {
  case "$1" in
    terminfo)
      cat <<'YAML'
  term-cursor:
    path: ../cursor
  term-screen:
    path: ../screen
YAML
      ;;
    reader)
      cat <<'YAML'
  term-cursor:
    path: ../cursor
  term-screen:
    path: ../screen
YAML
      ;;
    spinner)
      cat <<'YAML'
  term-cursor:
    path: ../cursor
  term-vt:
    path: ../vt
YAML
      ;;
    prompt)
      cat <<'YAML'
  term-color:
    path: ../color
  term-cursor:
    path: ../cursor
  term-reader:
    path: ../reader
  term-screen:
    path: ../screen
YAML
      ;;
    progress)
      cat <<'YAML'
  term-cursor:
    path: ../cursor
  term-screen:
    path: ../screen
  term-spinner:
    path: ../spinner
  term-vt:
    path: ../vt
YAML
      ;;
    *)
      return 1
      ;;
  esac
}

write_override_body() {
  local shard="$1"

  if ! local_dependency_lines "$shard" >/dev/null 2>&1; then
    return 1
  fi

  printf 'dependencies:\n'
  local_dependency_lines "$shard"
}

write_managed_override() {
  local shard="$1"
  local dir
  local file
  local body_file
  local managed_file

  dir="$(shard_path "$shard")" || return 1
  file="$dir/shard.override.yml"

  if ! write_override_body "$shard" >/dev/null 2>&1; then
    return 0
  fi

  body_file="$(mktemp)"
  managed_file="$(mktemp)"
  write_override_body "$shard" >"$body_file"
  {
    printf '# %s\n' "$MANAGED_MARKER"
    printf '# Remove with: scripts/validate-shards.sh --clean-local-overrides\n'
    cat "$body_file"
  } >"$managed_file"

  if [ -f "$file" ]; then
    if cmp -s "$file" "$managed_file"; then
      printf 'local override: %s already managed\n' "$shard"
      rm -f "$body_file" "$managed_file"
      return 0
    fi

    if cmp -s "$file" "$body_file"; then
      printf 'local override: %s already has compatible unmanaged override; leaving it in place\n' "$shard"
      rm -f "$body_file" "$managed_file"
      return 0
    fi

    if grep -q "$MANAGED_MARKER" "$file"; then
      cp "$managed_file" "$file"
      printf 'local override: refreshed %s\n' "$file"
      rm -f "$body_file" "$managed_file"
      return 0
    fi

    if [ "$FORCE_OVERRIDES" -eq 1 ]; then
      cp "$managed_file" "$file"
      printf 'local override: replaced existing %s\n' "$file"
      rm -f "$body_file" "$managed_file"
      return 0
    fi

    printf 'ERROR: %s exists and is not managed by this script.\n' "$file" >&2
    printf '       Re-run with --force-overrides only if replacing it is intentional.\n' >&2
    rm -f "$body_file" "$managed_file"
    return 1
  fi

  cp "$managed_file" "$file"
  printf 'local override: wrote %s\n' "$file"
  rm -f "$body_file" "$managed_file"
}

clean_managed_override() {
  local shard="$1"
  local dir
  local file

  dir="$(shard_path "$shard")" || return 1
  file="$dir/shard.override.yml"

  if [ ! -f "$file" ]; then
    return 0
  fi

  if grep -q "$MANAGED_MARKER" "$file"; then
    rm -f "$file"
    printf 'local override: removed %s\n' "$file"
    return 0
  fi

  printf 'local override: kept unmanaged %s\n' "$file"
}

ensure_no_unmanaged_override() {
  local shard="$1"
  local dir
  local file

  dir="$(shard_path "$shard")" || return 1
  file="$dir/shard.override.yml"

  if [ ! -f "$file" ]; then
    return 0
  fi

  if [ "$ALLOW_EXISTING_OVERRIDES" -eq 1 ]; then
    printf 'override: allowing existing %s\n' "$file"
    return 0
  fi

  printf 'ERROR: %s exists; released-mode validation would use local overrides.\n' "$file" >&2
  printf '       Use --local, --allow-existing-overrides, or remove the override.\n' >&2
  return 1
}

validate_shard_dirs() {
  local shard
  local dir

  for shard in "${SELECTED_SHARDS[@]}"; do
    if ! is_known_shard "$shard"; then
      printf 'ERROR: unknown shard "%s"\n' "$shard" >&2
      return 1
    fi

    dir="$(shard_path "$shard")" || return 1
    if [ ! -d "$dir" ]; then
      printf 'ERROR: missing shard directory %s\n' "$dir" >&2
      return 1
    fi
    if [ ! -f "$dir/shard.yml" ]; then
      printf 'ERROR: missing shard.yml in %s\n' "$dir" >&2
      return 1
    fi
  done
}

record_result() {
  local shard="$1"
  local phase="$2"
  local status="$3"

  RESULTS+=("$shard $phase $status")
}

run_in_shard() {
  local shard="$1"
  shift

  local dir
  dir="$(shard_path "$shard")" || return 1

  (
    cd "$dir" || exit 1
    "$@"
  )
}

run_phase() {
  local shard="$1"
  local phase="$2"
  shift 2

  printf '\n==> %s: %s\n' "$shard" "$phase"
  if run_in_shard "$shard" "$@"; then
    record_result "$shard" "$phase" "PASS"
  else
    record_result "$shard" "$phase" "FAIL"
    FAILURES=$((FAILURES + 1))
  fi
}

compile_examples() {
  local shard="$1"
  local dir
  local example
  local count=0
  local failed=0

  dir="$(shard_path "$shard")" || return 1
  if [ ! -d "$dir/examples" ]; then
    printf 'examples: %s has no examples directory; skipping\n' "$shard"
    return 0
  fi

  while IFS= read -r example; do
    count=$((count + 1))
    printf 'example: %s\n' "$example"
    if ! run_in_shard "$shard" crystal build --no-codegen --no-color "$example"; then
      failed=$((failed + 1))
    fi
  done < <(cd "$dir" && find examples -type f -name '*.cr' | sort)

  if [ "$count" -eq 0 ]; then
    printf 'examples: %s has no Crystal examples; skipping\n' "$shard"
    return 0
  fi

  if [ "$failed" -eq 0 ]; then
    printf 'examples: %s compiled %s file(s)\n' "$shard" "$count"
    return 0
  fi

  printf 'examples: %s failed %s of %s file(s)\n' "$shard" "$failed" "$count" >&2
  return 1
}

run_examples_phase() {
  local shard="$1"

  printf '\n==> %s: examples\n' "$shard"
  if compile_examples "$shard"; then
    record_result "$shard" "examples" "PASS"
  else
    record_result "$shard" "examples" "FAIL"
    FAILURES=$((FAILURES + 1))
  fi
}

print_summary() {
  local result

  printf '\nValidation summary:\n'
  for result in "${RESULTS[@]}"; do
    printf '  %s\n' "$result"
  done

  if [ "$FAILURES" -eq 0 ]; then
    printf '\nAll selected shard checks passed.\n'
  else
    printf '\n%s check(s) failed.\n' "$FAILURES" >&2
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --local)
      LOCAL_MODE=1
      ;;
    --clean-local-overrides)
      CLEAN_LOCAL=1
      ;;
    --force-overrides)
      FORCE_OVERRIDES=1
      ;;
    --allow-existing-overrides)
      ALLOW_EXISTING_OVERRIDES=1
      ;;
    --skip-install)
      SKIP_INSTALL=1
      ;;
    --skip-specs)
      SKIP_SPECS=1
      ;;
    --skip-examples)
      SKIP_EXAMPLES=1
      ;;
    --shards)
      if [ "$#" -lt 2 ]; then
        printf 'ERROR: --shards requires a comma-separated value\n' >&2
        exit 2
      fi
      IFS=',' read -r -a SELECTED_SHARDS <<<"$2"
      shift
      ;;
    --list-shards)
      LIST_SHARDS=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'ERROR: unknown option %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if ! validate_shard_dirs; then
  exit 2
fi

if [ "$LIST_SHARDS" -eq 1 ]; then
  for shard in "${SELECTED_SHARDS[@]}"; do
    printf '%-9s %s\n' "$shard" "$(shard_path "$shard")"
  done
  exit 0
fi

printf 'Crystal: '
crystal --version | head -n 1
printf 'Shards: '
shards --version

if [ "$CLEAN_LOCAL" -eq 1 ]; then
  for shard in "${SELECTED_SHARDS[@]}"; do
    clean_managed_override "$shard" || exit 1
  done
  exit 0
fi

if [ "$LOCAL_MODE" -eq 1 ]; then
  for shard in "${SELECTED_SHARDS[@]}"; do
    if ! write_managed_override "$shard"; then
      exit 1
    fi
  done
else
  for shard in "${SELECTED_SHARDS[@]}"; do
    if ! ensure_no_unmanaged_override "$shard"; then
      exit 1
    fi
  done
fi

for shard in "${SELECTED_SHARDS[@]}"; do
  if [ "$SKIP_INSTALL" -eq 0 ]; then
    run_phase "$shard" "install" shards install
  fi

  if [ "$SKIP_SPECS" -eq 0 ]; then
    run_phase "$shard" "spec" crystal spec --no-color
  fi

  if [ "$SKIP_EXAMPLES" -eq 0 ]; then
    run_examples_phase "$shard"
  fi
done

print_summary

if [ "$FAILURES" -ne 0 ]; then
  exit 1
fi
